services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    env_file:
      - .env

  backend:
    build: .
    container_name: backend
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env